include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_widgets
    - avoid_print
    - use_build_context_synchronously

analyzer:
  exclude:
    - build/**
    - "**/*.g.dart"
